version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
  db:
    image: 'postgres'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: timetracker
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: